### ISSUE TITLE
Test case suite fails on Neo4j v 2.3

### ISSUE THREAD

**Issue by corporatepiyush** [michaelklishin/neocons#84]
i am getting authentication exception on recently released Neo4j v 2.3 

Caused by: clojure.lang.ExceptionInfo: clj-http: status 401 {:orig-content-encoding nil, :trace-redirects ["http://localhost:7474/db/data/"], :request-time 150, :status 401, :headers {"date" "Wed, 28 Oct 2015 18:35:47 GMT", "content-type" "application/json; charset=UTF-8", "www-authenticate" "None", "connection" "close", "server" "Jetty(9.2.z-SNAPSHOT)"}, :body "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"} {:object {:orig-content-encoding nil, :trace-redirects ["http://localhost:7474/db/data/"], :request-time 150, :status 401, :headers {"date" "Wed, 28 Oct 2015 18:35:47 GMT", "content-type" "application/json; charset=UTF-8", "www-authenticate" "None", "connection" "close", "server" "Jetty(9.2.z-SNAPSHOT)"}, :body "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"}, :environment {client #<client$wrap_output_coercion$fn__2245 clj_http.client$wrap_output_coercion$fn__2245@4001d8c1>, req {:headers {"accept" "application/json", "User-Agent" "neocons.clj/3.1.0-beta3"}, :throw-entire-message? true, :url "http://localhost:7474/db/data/", :request-method :get}, map__2140 {:orig-content-encoding nil, :trace-redirects ["http://localhost:7474/db/data/"], :request-time 150, :status 401, :headers {"date" "Wed, 28 Oct 2015 18:35:47 GMT", "content-type" "application/json; charset=UTF-8", "www-authenticate" "None", "connection" "close", "server" "Jetty(9.2.z-SNAPSHOT)"}, :body "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"}, resp {:orig-content-encoding nil, :trace-redirects ["http://localhost:7474/db/data/"], :request-time 150, :status 401, :headers {"date" "Wed, 28 Oct 2015 18:35:47 GMT", "content-type" "application/json; charset=UTF-8", "www-authenticate" "None", "connection" "close", "server" "Jetty(9.2.z-SNAPSHOT)"}, :body "{\n  \"errors\" : [ {\n    \"message\" : \"No authorization header supplied.\",\n    \"code\" : \"Neo.ClientError.Security.AuthorizationFailed\"\n  } ]\n}"}, status 401}}
	at clj_http.client$wrap_exceptions$fn__2139.invoke(client.clj:146)
	at clj_http.client$wrap_accept$fn__2285.invoke(client.clj:463)
	at clj_http.client$wrap_accept_encoding$fn__2291.invoke(client.clj:478)
	at clj_http.client$wrap_content_type$fn__2280.invoke(client.clj:454)
	at clj_http.client$wrap_form_params$fn__2329.invoke(client.clj:565)
	at clj_http.client$wrap_nested_params$fn__2347.invoke(client.clj:589)
	at clj_http.client$wrap_method$fn__2324.invoke(client.clj:548)
	at clj_http.cookies$wrap_cookies$fn__261.invoke(cookies.clj:121)
	at clj_http.links$wrap_links$fn__298.invoke(links.clj:50)
	at clj_http.client$wrap_unknown_host$fn__2356.invoke(client.clj:608)
	at clj_http.client$get.doInvoke(client.clj:715)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojurewerkz.neocons.rest$GET.doInvoke(rest.clj:61)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojurewerkz.neocons.rest$connect.invoke(rest.clj:97)
	at clojurewerkz.neocons.rest$connect.invoke(rest.clj:92)
	at clojurewerkz.neocons.rest.test.batch_operations_test$eval3406.invoke(batch_operations_test.clj:17)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 33 more
Tests failed.

**Comment by corporatepiyush** [comment]
Never mind. found the solution 

# Disable authorization
dbms.security.auth_enabled=false

you may close it  ;)

**Comment by ducky427** [comment]
Just FYI, I've created a branch to test against Neo4j 2.3.0. All our tests [pass](https://travis-ci.org/michaelklishin/michaelklishin/neocons/builds/87963312).
