### ISSUE TITLE
tquery...  IllegalArgumentException Host URL cannot be nil  clj-http.client/post 

### ISSUE THREAD

**Issue by carld** [michaelklishin/neocons#92]
I've had success working with a local Neo4j service and the neocons clojure library. I've hit trouble trying to deploy the same code to a production environment.

In this case the REPL, `heroku run lein repl`,  shows there's a connection object and the URL obtained from `System/getenv` is in the expected format `http://<user>:<pass>@resourceId.station-name.stations.graphenedb.com:24789/db/data`

```
user=> (require '[clojurewerkz.neocons.rest.cypher :as cy])
nil
user=> (require '[clojurewerkz.neocons.rest :as nr])
nil
user=> (cy/tquery (nr/connect (System/getenv "GRAPHENEDB_URL")) "return 1")

IllegalArgumentException Host URL cannot be nil  clj-http.client/post (client.clj:1166)
user=> 
user=> (nr/connect (System/getenv "GRAPHENEDB_URL")
  #_=> )
#clojurewerkz.neocons.rest.Connection{:endpoint #clojurewerkz.neocons.rest.Neo4JEndpoint{:version nil, :node-uri nil, :relationships-uri "<CREDENTIALS FILTERED>", :node-index-uri nil, :relationship-index-uri nil, :relationship-types-uri nil, :batch-uri nil, :extensions-info-uri nil, :extensions nil, :reference-node-uri nil, :uri "<CREDENTIALS FILTERED>", :cypher-uri nil, :transaction-uri nil}, :http-auth {:basic-auth ["<CREDENTIALS FILTERED>" "<CREDENTIALS FILTERED>"]}, :options {:headers {"User-Agent" "neocons.clj/3.1.0-beta3"}}}
```

Call stack
```
java.lang.IllegalArgumentException: Host URL cannot be nil
	at clj_http.client$post.invokeStatic(client.clj:1166)
	at clj_http.client$post.doInvoke(client.clj:1163)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojurewerkz.neocons.rest$POST.invokeStatic(rest.clj:66)
	at clojurewerkz.neocons.rest$POST.doInvoke(rest.clj:63)
	at clojure.lang.RestFn.invoke(RestFn.java:464)
	at clojurewerkz.neocons.rest.cypher$query.invokeStatic(cypher.clj:50)
	at clojurewerkz.neocons.rest.cypher$query.invoke(cypher.clj:45)
	at clojure.core$comp$fn__4727.invoke(core.clj:2462)
```

In project.clj is

```
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [compojure "1.5.2"]
                 [clojurewerkz/neocons "3.1.0"]
                 [ring/ring-json "0.4.0"]
                 [hickory "0.7.1"]
                 [clj-http "3.4.1"]
                 [cheshire "5.7.0"]
                 [com.cemerick/friend "0.2.3"]
                 [org.clojure/data.csv "0.1.3"]
                 [ring/ring-jetty-adapter "1.5.1"]
                 [environ "1.1.0"]]
```

Thanks for any help!

**Comment by carld** [comment]
Following up it looks like it's due to result of `cypher-query-location-for`

```
user=> (cy/cypher-query-location-for (nr/connect (System/getenv "GRAPHENEDB_URL")))
nil
```

**Comment by carld** [comment]
In the connection, `:cypher-uri nil`.

Probably not related to neocons code then.

**Comment by carld** [comment]
For any passer by, this would happen when the url path did not end with  "/db/data".

The code below resolves this

```
(def db-url                                                                          
  (let [url  (get (System/getenv) "GRAPHENEDB_URL" "http://(redacted)@localhost:7474/db/data")]
    (if (clojure.string/ends-with? url "/db/data")                                   
      url                                                                            
      (str url "/db/data"))))                                                        

(def conn  (nr/connect db-url))
```
